"""Authenticated HLS relay for the playlists generated by generate.py."""

from __future__ import annotations

import asyncio
import hmac
import os
import re
import secrets
import time
import urllib.parse
from contextlib import asynccontextmanager
from dataclasses import dataclass, field
from pathlib import Path

import anyio
import httpx
from fastapi import FastAPI, HTTPException, Request
from fastapi.responses import FileResponse, PlainTextResponse, StreamingResponse
from starlette.background import BackgroundTask

VIDEO_ID_RE = re.compile(r"^[A-Za-z0-9_-]{6,}$")
TOKEN_RE = re.compile(r"^[A-Za-z0-9_-]{32,}$")
URI_ATTRIBUTE_RE = re.compile(r'(URI=")([^"]+)(")')
SESSION_TTL_SECONDS = 4 * 60 * 60
UPSTREAM_USER_AGENT = "Mozilla/5.0 (compatible; youtube-m3u8-proxy/1.0)"


@dataclass
class Settings:
    access_token: str
    playlist_dir: Path

    @classmethod
    def from_environment(cls) -> "Settings":
        token = os.environ.get("ACCESS_TOKEN", "")
        if not TOKEN_RE.fullmatch(token):
            raise RuntimeError("ACCESS_TOKEN must have at least 32 URL-safe characters")
        return cls(token, Path(os.environ.get("PLAYLIST_DIR", "playlists")))


@dataclass
class Session:
    video_id: str
    created_at: float
    video: dict
    audio: dict
    assets: dict[str, str] = field(default_factory=dict)


class SessionStore:
    def __init__(self) -> None:
        self.sessions: dict[str, Session] = {}
        self.lock = asyncio.Lock()

    async def create(self, video_id: str) -> tuple[str, Session]:
        pair = await anyio.to_thread.run_sync(resolve_hls_pair, video_id)
        if pair is None:
            raise HTTPException(502, "No compatible HLS audio/video pair was found")
        session = Session(video_id, time.monotonic(), *pair)
        async with self.lock:
            self._purge()
            session_id = secrets.token_urlsafe(18)
            self.sessions[session_id] = session
        return session_id, session

    async def get(self, session_id: str) -> Session:
        async with self.lock:
            self._purge()
            session = self.sessions.get(session_id)
        if session is None:
            raise HTTPException(410, "HLS session expired; reload the playlist item")
        return session

    def _purge(self) -> None:
        cutoff = time.monotonic() - SESSION_TTL_SECONDS
        self.sessions = {key: value for key, value in self.sessions.items() if value.created_at >= cutoff}


def is_hls_format(item: dict) -> bool:
    return str(item.get("protocol", "")).startswith("m3u8") and bool(item.get("url"))


def best_hls_pair(formats: list[dict]) -> tuple[dict, dict] | None:
    # rPlayTV's FFmpeg stack is reliably compatible with AVC/H.264. Do not
    # silently fall back to VP9/AV1, which would make a playlist entry fail.
    videos = [item for item in formats if is_hls_format(item) and str(item.get("vcodec", "")).startswith("avc")]
    audios = []
    for item in formats:
        codec = item.get("acodec")
        if not is_hls_format(item) or item.get("vcodec") not in {None, "none"}:
            continue
        # yt-dlp sometimes reports a null codec for a valid YouTube HLS AAC
        # rendition. Known non-AAC codecs are deliberately excluded.
        if codec not in {None, "none", "", "null"} and not str(codec).startswith("mp4a"):
            continue
        audios.append(item)
    if not videos or not audios:
        return None
    target_height = 360
    video = max(videos, key=lambda item: (
        str(item.get("vcodec", "")).startswith("avc"),
        -abs((item.get("height") or 0) - target_height),
        -(item.get("height") or 0),
    ))
    audio = max(audios, key=lambda item: (
        str(item.get("acodec", "")).startswith("mp4a"), item.get("abr") or 0, item.get("tbr") or 0,
    ))
    return video, audio


def resolve_hls_pair(video_id: str) -> tuple[dict, dict] | None:
    if not VIDEO_ID_RE.fullmatch(video_id):
        return None
    import yt_dlp

    options = {"quiet": True, "no_warnings": True, "noplaylist": True}
    with yt_dlp.YoutubeDL(options) as downloader:
        info = downloader.extract_info(f"https://www.youtube.com/watch?v={video_id}", download=False)
    return best_hls_pair(info.get("formats") or []) if isinstance(info, dict) else None


def master_manifest(base: str, session_id: str, session: Session) -> str:
    video, audio = session.video, session.audio
    video_bandwidth = int((video.get("tbr") or 0) * 1000)
    audio_bandwidth = int((audio.get("tbr") or audio.get("abr") or 0) * 1000)
    video_codec = video.get("vcodec") or "avc1.4d401e"
    audio_codec = audio.get("acodec") or "mp4a.40.2"
    codecs = f"{video_codec},{audio_codec}"
    attributes = f'BANDWIDTH={max(video_bandwidth + audio_bandwidth, 1)},CODECS="{codecs}",AUDIO="audio"'
    if video.get("width") and video.get("height"):
        attributes += f',RESOLUTION={video["width"]}x{video["height"]}'
    return "\n".join((
        "#EXTM3U", "#EXT-X-VERSION:7",
        f'#EXT-X-MEDIA:TYPE=AUDIO,GROUP-ID="audio",NAME="Audio",DEFAULT=YES,AUTOSELECT=YES,URI="{base}/{session_id}/manifest/audio.m3u8"',
        f"#EXT-X-STREAM-INF:{attributes}", f"{base}/{session_id}/manifest/video.m3u8", "",
    ))


def rewrite_manifest(text: str, source_url: str, asset_url) -> str:
    def rewrite(raw_url: str) -> str:
        return asset_url(urllib.parse.urljoin(source_url, raw_url))

    rewritten: list[str] = []
    for line in text.splitlines():
        if line.startswith("#"):
            rewritten.append(URI_ATTRIBUTE_RE.sub(lambda match: match.group(1) + rewrite(match.group(2)) + match.group(3), line))
        elif line.strip():
            rewritten.append(rewrite(line.strip()))
        else:
            rewritten.append(line)
    return "\n".join(rewritten) + "\n"


def is_hls_response(url: str, content_type: str | None) -> bool:
    """Identify nested media playlists, which must be rewritten as well."""
    return ".m3u8" in urllib.parse.urlparse(url).path.lower() or "mpegurl" in (content_type or "").lower()


def require_token(settings: Settings, token: str) -> None:
    if not hmac.compare_digest(token, settings.access_token):
        raise HTTPException(404, "Not found")


@asynccontextmanager
async def lifespan(app: FastAPI):
    app.state.settings = Settings.from_environment()
    app.state.sessions = SessionStore()
    app.state.client = httpx.AsyncClient(follow_redirects=True, timeout=httpx.Timeout(30.0, read=90.0), headers={"User-Agent": UPSTREAM_USER_AGENT})
    yield
    await app.state.client.aclose()


app = FastAPI(title="youtube-m3u8 HLS proxy", docs_url=None, redoc_url=None, lifespan=lifespan)


@app.get("/healthz")
async def healthz() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/p/{token}/playlist.m3u8")
async def playlist(token: str, request: Request):
    require_token(request.app.state.settings, token)
    path = request.app.state.settings.playlist_dir / "all.m3u8"
    if not path.is_file():
        raise HTTPException(503, "Playlist has not been generated yet")
    return FileResponse(path, media_type="application/x-mpegURL", headers={"Cache-Control": "no-store"})


@app.get("/p/{token}/hls/{video_id}/master.m3u8")
async def master(token: str, video_id: str, request: Request):
    require_token(request.app.state.settings, token)
    if not VIDEO_ID_RE.fullmatch(video_id):
        raise HTTPException(404, "Not found")
    try:
        session_id, session = await request.app.state.sessions.create(video_id)
    except HTTPException:
        raise
    except Exception as error:
        raise HTTPException(502, f"Could not resolve YouTube HLS: {error}") from error
    base = f"/p/{token}/hls"
    return PlainTextResponse(master_manifest(base, session_id, session), media_type="application/vnd.apple.mpegurl", headers={"Cache-Control": "no-store"})


@app.get("/p/{token}/hls/{session_id}/manifest/{track}.m3u8")
async def child_manifest(token: str, session_id: str, track: str, request: Request):
    require_token(request.app.state.settings, token)
    if track not in {"video", "audio"}:
        raise HTTPException(404, "Not found")
    session = await request.app.state.sessions.get(session_id)
    source_url = session.video["url"] if track == "video" else session.audio["url"]
    try:
        response = await request.app.state.client.get(source_url)
        response.raise_for_status()
    except httpx.HTTPError as error:
        raise HTTPException(502, f"Could not retrieve upstream HLS manifest: {error}") from error

    def asset_url(url: str) -> str:
        asset_id = secrets.token_urlsafe(16)
        session.assets[asset_id] = url
        return f"/p/{token}/hls/{session_id}/asset/{asset_id}"

    return PlainTextResponse(rewrite_manifest(response.text, source_url, asset_url), media_type="application/vnd.apple.mpegurl", headers={"Cache-Control": "no-store"})


@app.get("/p/{token}/hls/{session_id}/asset/{asset_id}")
async def asset(token: str, session_id: str, asset_id: str, request: Request):
    require_token(request.app.state.settings, token)
    session = await request.app.state.sessions.get(session_id)
    source_url = session.assets.get(asset_id)
    if source_url is None:
        raise HTTPException(404, "Not found")
    headers = {"Accept-Encoding": "identity"}
    if request.headers.get("range"):
        headers["Range"] = request.headers["range"]
    try:
        upstream = await request.app.state.client.send(request.app.state.client.build_request("GET", source_url, headers=headers), stream=True)
    except httpx.HTTPError as error:
        raise HTTPException(502, f"Could not retrieve upstream media: {error}") from error
    if is_hls_response(source_url, upstream.headers.get("content-type")):
        try:
            body = (await upstream.aread()).decode("utf-8")
            upstream.raise_for_status()
        except (UnicodeDecodeError, httpx.HTTPError) as error:
            await upstream.aclose()
            raise HTTPException(502, f"Could not retrieve nested HLS manifest: {error}") from error
        await upstream.aclose()

        def nested_asset_url(url: str) -> str:
            nested_id = secrets.token_urlsafe(16)
            session.assets[nested_id] = url
            return f"/p/{token}/hls/{session_id}/asset/{nested_id}"

        return PlainTextResponse(rewrite_manifest(body, source_url, nested_asset_url), media_type="application/vnd.apple.mpegurl", headers={"Cache-Control": "no-store"})
    response_headers = {key: value for key, value in upstream.headers.items() if key.lower() in {"content-length", "content-range", "accept-ranges", "content-type", "last-modified", "etag"}}
    response_headers["Cache-Control"] = "no-store"
    response_headers["X-Accel-Buffering"] = "no"
    return StreamingResponse(upstream.aiter_raw(), status_code=upstream.status_code, media_type=upstream.headers.get("content-type"), headers=response_headers, background=BackgroundTask(upstream.aclose))
